services:
  backend:
    build: 
      context: ./api
    container_name: backend
    expose:
      - "8022"
    ports:
      - "8022:8022"
    environment:
      - FASTAPI_PORT=8022
      - API_URL=http://localhost:8022
    command: fastapi run main.py --port 8022

  frontend:
    build: 
      context: ./svelte
    container_name: frontend
    ports:
      - "4000:4000"
    environment:
      - API_URL=http://localhost:8022
      - PORT=4000
    command: ["pnpm", "run", "preview", "--host", "--port", "4000"]
