services:
  backend:
    build: 
      context: ./api
    container_name: backend
    expose:
      - "8000"
    ports:
      - "8000:8000"
    environment:
      - FASTAPI_PORT=8000
      - API_URL=http://backend:8000
    command: fastapi run main.py --port 8000

  frontend:
    build: 
      context: ./frontend
    container_name: frontend
    ports:
      - "4000:4000"
    environment:
      - API_URL=http://backend:8000
      - PORT=4000
    command: ["node", "build"]
